config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "questions#ask"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
   get "ask",    to: "questions#ask"
  get "answer", to: "questions#answer"
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask; end

  def answer
    raw = params[:question].to_s
    @question = raw.strip          # mostra na tela exatamente o que o usuário digitou
    q = @question.downcase         # versão normalizada para comparar

    @answer =
      if q == "i am going to work"
        "Great!"
      elsif q.end_with?("?")       # << Ruby: end_with? (sem 's')
        "Silly question, get dressed and go to work!"
      else
        "I don't care, get dressed and go to work!"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class= "container-narrow">
<h1>Coach answer</h1>
<div class=chat-bubble>
<small>You:<small>
<p class="mb-0"><%= params[:question] %></p>
</div>
<div class="chat-bubble answer">
<small>Coach:<small>
<p class="mb-0"><%= @answer %></p>
</div>
<%= link_to "Ask another question", ask_path, class: "btn btn-link back-link" %>
</div>

app/views/questions/ask.html.erb
<div class="container-narrow">
<h1>Stupid Coaching</h1>
<p class="test-muted">Ask your coach anything</p>

<form action="<%= answer_path %>" method="get" data-turbo="false" class="ask-form">
  <input
  type="text"
  name="question"
  class="form-control"
  placeholder="Type your question"
  value="<%= params[:question]%>">
  <button type="submit" class="btn btn-primary">Ask</button>
</form>
</div>